apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-pod
      labels:
        app: webserver
    spec:
      containers:
      - name: first-container
        image: nginx:1.10
        ports:
        - containerPort: 80

