apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels:
    app: my-first-pod-label
spec:
  containers:
  - name: my-first-container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP