version: "3.7"
services:
  wordpress:
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_PASSWORD=pw
      - WORDPRESS_DB_USER=root
    links:
      - wordpressdb:mysql
    ports:
      - "80"
    stdin_open: true
    tty: true
  wordpressdb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=wordpress
    stdin_open: true
    tty: true